### ISSUE TITLE
[Question] What is the internal logic in Snipgenie for flagging a SNP? (Comparison with manual analysis)

### ISSUE THREAD

**Issue by jolespin** [dmnfarrell/snpgenie#4]
Our team has conducted WGS against various human cell lines in order to validate the presence of a molecule we were hoping to detect. We then sought to analyze sequence integrity (SNPs and indels) of particular regions using your tool Snipgenie. 

Snipgenie returned what we understand to mean no SNPs or indels (see snapshot from calls.vcf file). Oddly, when we align our reads to each of these regions and look at the tracks with a conventional viewer (i.e. IGV), we observe what look like SNPs. 

I've attached sample alignment tracks for reference. Dark grey denotes a perfect match to the reference; whereas, the other colors denote particular nucleotides that deviate from the reference. Now, the tracks are not completely grey, and we're wondering how we can reconcile the Snipgenie output with this result. 

Base quality was one thought as many of these mismatches are comprised of >1 base called at that position, but this doesn't seem to be the case for all of them. For instance, if you look at the files labeled "...YAC Region...", you'll notice a few spots that have what would appear to be only one variant nucleotide and with high coverage. 

**Can you explain what's happening in the backend where Snipgenie decides not to flag these regions as SNPs?**

And to get the tool to run such that the output better mirrors the alignment results, are there certain parameters that you'd recommend playing with to accomplish that goal?

Here's the current command: 

```
N_JOBS=4
REF=References/antibiotic-myc-yac.concatenated.fa
REF_NAME=$(basename $REF .fa)
OUT_DIR=snipgenie_output/${REF_NAME}
mkdir -p ${OUT_DIR}
N="snipgenie__${REF_NAME}"
CMD="source activate snippy_env && snipgenie -r ${REF} -i reads -o ${OUT_DIR} -t ${N_JOBS}"
sbatch -J ${N} -p ind-shared -N 1 -c ${N_JOBS} --ntasks-per-node=1 -A jcl123 -o logs/${N}.o -e logs/${N}.e --export=ALL -t 48:00:00 --mem=48G --wrap="${CMD}"
```

Here's the structure of the `reads/` directory: 

```
(base) [jespinoz@login02 SOLEXASEQ-1709]$ tree reads
reads
├── HAC1_15_Enriched_S5
│   ├── HAC1_15_Enriched_S5_1.fastq.gz -> ../../preprocess_output/HAC1_15_Enriched_S5/output/trimmed_1.fastq.gz
│   └── HAC1_15_Enriched_S5_2.fastq.gz -> ../../preprocess_output/HAC1_15_Enriched_S5/output/trimmed_2.fastq.gz
└── HAC4_1_1_Enriched_S6
    ├── HAC4_1_1_Enriched_S6_1.fastq.gz -> ../../preprocess_output/HAC4_1_1_Enriched_S6/output/trimmed_1.fastq.gz
    └── HAC4_1_1_Enriched_S6_2.fastq.gz -> ../../preprocess_output/HAC4_1_1_Enriched_S6/output/trimmed_2.fastq.gz
```

Please let me know if you have any other questions or need any additional information.

![11142-23_CloneReadsMappingtoYAC Region 751,339-757,911_Autoscaled](https://github.com/dmnfarrell/snipgenie/assets/9061708/b5ffe16a-93fd-4f4b-a63c-a748cb05431a)
![11142-23_CloneReadsMappingtoYAC Region 751,339-757,911](https://github.com/dmnfarrell/snipgenie/assets/9061708/e01ff6fc-1c04-4c65-9cdd-15dfd28ce809)
![11142023_CloneReadsMappingtoAntibiotic Resistance Gene Region 555,068-558,944](https://github.com/dmnfarrell/snipgenie/assets/9061708/76f79165-2cbb-432b-a721-51816902bab7)
![11142023_CloneReadsMappingtoMyco Region 378,324-380,510](https://github.com/dmnfarrell/snipgenie/assets/9061708/389480c7-32b2-4de2-b56c-69c69aba8ac0)
<img width="1289" alt="CallsfromJoshsSNIPGenieAnalysis" src="https://github.com/dmnfarrell/snipgenie/assets/9061708/3cb264cf-cff3-4354-85e3-0681e6064dd6">

**Comment by dmnfarrell** [comment]
It's saying this because the program is designed to get a core alignment of variant sites at the end. It does this by extracting them from the filtered vcf:
1. uninformative snps are removed be default since if all samples have the same snp it adds nothing to the diversity. This is for the purpose of making a phylogeny.
2. If there is a missing site (with no call) in ANY sample, the position is removed for all samples by default. It should say how many missing sites where found in the output.
Either of these might be removing the snps at the end. I could probably add an option to allow missing or uninformative sites if it is useful.

Also if these are human genes then they are diploid? The program assumes a ploidy of 1. Though if you are getting results in calls.vcf this may not be an issue.

**Comment by dmnfarrell** [comment]
You should see output like this:

```
making SNP matrix
-----------------
found 42 sites for core snps
2 sites with at least one missing sample
5 uninformative sites
```

**Comment by jolespin** [comment]
Thank you, this is very informative!

@dmnfarrell would this be in one of the log files? 

<img width="954" alt="image" src="https://github.com/dmnfarrell/snipgenie/assets/9061708/614c31f2-c8a6-414e-9077-e75623a995ea">


Here's the log file from stdout: 

```
(base) [jespinoz@login02 SOLEXASEQ-1709]$ cat logs/snipgenie__antibiotic-myc-yac.concatenated.o
The following options were supplied
time:  31/10/2023 16:46:54
-------
input : ['reads']
labelsep : _
labelindex : 0
reference : References/antibiotic-myc-yac.concatenated.fa
species : None
gb_file : None
threads : 4
overwrite : False
trim : False
unmapped : False
quality : 25
filters : QUAL>=40 && FORMAT/DP>=30 && DP4>=4
mask : None
custom_filters : False
platform : illumina
aligner : bwa
buildtree : False
bootstraps : 100
outdir : snipgenie_output/antibiotic-myc-yac.concatenated
qc : False
dummy : False
test : False
version : False
omit_samples : []
get_stats : True
logfile : snipgenie_output/antibiotic-myc-yac.concatenated/run.log

2 samples were loaded:
----------------------
  sample  ... read_length
0   HAC1  ...         148
1   HAC4  ...         148

[2 rows x 6 columns]

building index
indexing..
bwa index References/antibiotic-myc-yac.concatenated.fa
aligning files
--------------
Using reference genome: References/antibiotic-myc-yac.concatenated.fa
0/2 samples already aligned
bwa mem -M -t 4  References/antibiotic-myc-yac.concatenated.fa "/expanse/projects/jcl110/ArtificialChromosomes/SOLEXASEQ-1709/reads/HAC1_15_Enriched_S5/HAC1_15_Enriched_S5_1.fastq.gz" "/expanse/projects/jcl110/ArtificialChromosomes/SOLEXASEQ-1709/reads/HAC1_15_Enriched_S5/HAC1_15_Enriched_S5_2.fastq.gz" | samtools view -F 4 -bt - | samtools sort -o snipgenie_output/antibiotic-myc-yac.concatenated/mapped/HAC1.bam
indexing HAC1
samtools index snipgenie_output/antibiotic-myc-yac.concatenated/mapped/HAC1.bam
bwa mem -M -t 4  References/antibiotic-myc-yac.concatenated.fa "/expanse/projects/jcl110/ArtificialChromosomes/SOLEXASEQ-1709/reads/HAC4_1_1_Enriched_S6/HAC4_1_1_Enriched_S6_1.fastq.gz" "/expanse/projects/jcl110/ArtificialChromosomes/SOLEXASEQ-1709/reads/HAC4_1_1_Enriched_S6/HAC4_1_1_Enriched_S6_2.fastq.gz" | samtools view -F 4 -bt - | samtools sort -o snipgenie_output/antibiotic-myc-yac.concatenated/mapped/HAC4.bam
indexing HAC4
samtools index snipgenie_output/antibiotic-myc-yac.concatenated/mapped/HAC4.bam

calling variants
----------------
running mpileup..
[   1  969 1938 2906 3875]
parallel bcftools mpileup -r {1} -a "AD,ADF,ADR,DP,SP,INFO/AD,INFO/ADF,INFO/ADR" -O b --max-depth 500 --min-MQ 60 -o {2} -f References/antibiotic-myc-yac.concatenated.fa /expanse/projects/jcl110/ArtificialChromosomes/SOLEXASEQ-1709/snipgenie_output/antibiotic-myc-yac.concatenated/mapped/HAC1.bam /expanse/projects/jcl110/ArtificialChromosomes/SOLEXASEQ-1709/snipgenie_output/antibiotic-myc-yac.concatenated/mapped/HAC4.bam ::: "Antibiotic_Resistance_Gene_Region__555068-558944":1-968 "Antibiotic_Resistance_Gene_Region__555068-558944":969-1937 "Antibiotic_Resistance_Gene_Region__555068-558944":1938-2905 "Antibiotic_Resistance_Gene_Region__555068-558944":2906-3874 :::+ snipgenie_output/antibiotic-myc-yac.concatenated/tmp/1-968.bcf snipgenie_output/antibiotic-myc-yac.concatenated/tmp/969-1937.bcf snipgenie_output/antibiotic-myc-yac.concatenated/tmp/1938-2905.bcf snipgenie_output/antibiotic-myc-yac.concatenated/tmp/2906-3874.bcf
bcftools concat snipgenie_output/antibiotic-myc-yac.concatenated/tmp/1-968.bcf snipgenie_output/antibiotic-myc-yac.concatenated/tmp/969-1937.bcf snipgenie_output/antibiotic-myc-yac.concatenated/tmp/1938-2905.bcf snipgenie_output/antibiotic-myc-yac.concatenated/tmp/2906-3874.bcf -O b -o snipgenie_output/antibiotic-myc-yac.concatenated/raw.bcf
calling variants..
bcftools call --ploidy 1 -m -v -o snipgenie_output/antibiotic-myc-yac.concatenated/calls.vcf snipgenie_output/antibiotic-myc-yac.concatenated/raw.bcf
2 sites called as variants
bcftools reheader --samples snipgenie_output/antibiotic-myc-yac.concatenated/samples.txt -o /tmp/calls.vcf snipgenie_output/antibiotic-myc-yac.concatenated/calls.vcf
bcftools filter -i "QUAL>=40 && FORMAT/DP>=30 && DP4>=4" -o snipgenie_output/antibiotic-myc-yac.concatenated/filtered.vcf.gz -O z snipgenie_output/antibiotic-myc-yac.concatenated/calls.vcf
splitting snps and indels..
bcftools view -v snps -o snipgenie_output/antibiotic-myc-yac.concatenated/snps.vcf.gz -O z snipgenie_output/antibiotic-myc-yac.concatenated/filtered.vcf.gz
bcftools view -v indels -o snipgenie_output/antibiotic-myc-yac.concatenated/indels.vcf.gz -O z snipgenie_output/antibiotic-myc-yac.concatenated/filtered.vcf.gz
took 1.0 seconds
snipgenie_output/antibiotic-myc-yac.concatenated/snps.vcf.gz

making SNP matrix
-----------------
found 0 sites for core snps
0 sites with at least one missing sample
0 uninformative sites
no sites found may mean:
- samples are identical
- one sample is too different due to poor coverage/depth
this may be caused by contamination or low quality data

Done. Sample summary:
---------------------
  sample                   name1  ... coverage  meandepth
0   HAC1   HAC1_15_Enriched_S5_1  ...    61.11       3.05
1   HAC4  HAC4_1_1_Enriched_S6_1  ...    66.35       4.28

[2 rows x 7 columns]
```

**Comment by GBIRCHAK** [comment]
Hi @dmnfarrell

Thank you for the prompt reply! It's already been very informative.

I'll jump in with a couple of questions as @jolespin and I are both working on this.

So it sounds like nothing was called for at least one of these three reasons:

1) When there was significant coverage and an apparent SNP, it was conserved across both samples.

2) When there was a divergent SNP across the samples, coverage was not high enough to flag it as a SNP.

3) Multiple nucleotides were called at the same site within the same sample (i.e. read quality was too poor).

If I have all of that right, then I have two questions: What depth is needed to call a variant a SNP? How exactly is "uninformative" defined? My assumption is that this would contain reasons 2 and 3 that I've listed above, yet @jolespin has output that says otherwise.

Appreciate the time!

**Comment by jolespin** [comment]
@dmnfarrell 

> Also if these are human genes then they are diploid? 

We aligned to an artificial chromosome which would be considered haploid. 

Is there a recommended citation for SnipGenie?  (e.g., https://pubmed.ncbi.nlm.nih.gov/34970617/)

**Comment by dmnfarrell** [comment]
Hi. Ok so it isn't the latter steps that are the issue. You are getting 2 sites called and then none. So maybe they are being filtered out. The default filter is 'QUAL>=40 && FORMAT/DP>=30 && DP4>=4' as you can see in the output. You can provide an empty string to have no filter. So use -f "". This might make a big difference especially if you have low mean depth. 

* QUAL >= 40: This condition filters variants based on their Phred-scaled quality score (QUAL). The QUAL score represents the probability that the variant call is incorrect. A higher QUAL score indicates higher confidence in the variant call. In this case, variants with a QUAL score greater than or equal to 40 are retained.
* FORMAT/DP >= 30: This condition filters variants based on the depth of coverage (DP) information in the sample-level FORMAT field. The DP is the total read depth at a variant site. The condition requires that the DP for a sample is greater than or equal to 30. This helps filter out variants with low coverage.
* DP4 >= 4: This condition involves the DP4 field in the FORMAT field. The DP4 field typically represents the high-quality base counts for forward and reverse strands on the reference and alternate alleles. The condition requires that at least 4 high-quality bases support the variant allele (i.e., the sum of forward and reverse counts for the alternate allele is 4 or more).

Perhaps the default should be empty but then people would not know and get a lot rubbish snps..

"uninformative" just means its the same in all samples so can be ignored for making a phylogeny. This isn't the issue here though.

**Comment by dmnfarrell** [comment]
Yes https://pubmed.ncbi.nlm.nih.gov/34970617/ is the best citation.
